server:
  port: 7070

spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:file:~/test
    username: sa
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: false
    hibernate:
      ddl-auto: create
